apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
# Here we define every config to be applied,
# in this specific component (Deployment in this case).
spec:
  replicas: 1
  selector:
    # With this selector we connect the Deployment component with the pods below
    matchLabels:
      app: mongodb
  # Here we define the BluePrint of the pod,
  # this config applies specifically in the pod.
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
